services:
  # Shopify App
  app:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_STRING}:5432/${DB_NAME}
      - SHOPIFY_API_KEY=${SHOPIFY_API_KEY}
      - SHOPIFY_API_SECRET=${SHOPIFY_API_SECRET}
      - SCOPES=${SCOPES}
      - HOST=${HOST}
      - SHOPIFY_APP_URL=${SHOPIFY_APP_URL}
      - PROMETHEUS_URL=http://prometheus:9090

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
