services:
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://${GRAFANA_ROOT_URL}
    volumes:
      - grafana_data:/var/lib/grafana
    entrypoint:
      - sh
      - -c
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        echo 'apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            orgId: 1
            url: http://cmb82dpzj00aakz9zfvgmselh-prometheus:9090
            basicAuth: false
            isDefault: true
            editable: false' > /etc/grafana/provisioning/datasources/prometheus.yml &&
        /run.sh
    networks:
      - monitoring-network

volumes:
  grafana_data:

networks:
  monitoring-network:
    external: true