# Prometheus configuration file for production
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "shopify-app"
    static_configs:
      - targets: ["app:8080"] 
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s